package com.example.ui.screens

import android.graphics.Bitmap
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.PickVisualMediaRequest
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.*
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import coil.compose.AsyncImage
import com.example.model.UserEntity
import com.example.moderation.ImageSafetyModerator
import com.example.moderation.ModerationResult
import com.example.ui.components.AvatarView
import com.example.ui.theme.*
import com.example.util.CountryHelper
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlin.random.Random

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun UserProfileSetupDialog(
    initialUser: UserEntity? = null,
    onDismiss: () -> Unit,
    onSaveProfile: (
        nickname: String,
        age: Int,
        country: String,
        bio: String,
        avatarUrl: String,
        gender: String
    ) -> Unit,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()

    // 1 = Photo, 2 = Personal Info, 3 = Profile Preview
    var currentStep by remember { mutableIntStateOf(1) }

    // Unique generated User ID
    val autoGeneratedUserId = remember {
        initialUser?.userId ?: (Random.nextLong(100000, 999999))
    }

    // Step 1: Photo & Moderation states
    var avatarUriString by remember { mutableStateOf(initialUser?.avatarUrl ?: "avatar_user") }
    var rawSelectedUri by remember { mutableStateOf<Uri?>(null) }
    var isCompressingAndUploading by remember { mutableStateOf(false) }
    var uploadProgress by remember { mutableFloatStateOf(0f) }
    var moderationResult by remember { mutableStateOf<ModerationResult?>(null) }
    var cropZoom by remember { mutableFloatStateOf(1f) }
    var showCropControls by remember { mutableStateOf(false) }

    // Step 2: Personal info
    var nickname by remember { mutableStateOf(initialUser?.nickname ?: "StarKing${autoGeneratedUserId % 1000}") }
    var age by remember {
        val initialAge = initialUser?.dob?.split("-")?.firstOrNull()?.toIntOrNull()?.let { 2026 - it } ?: 22
        mutableIntStateOf(if (initialAge in 18..99) initialAge else 22)
    }
    var selectedCountry by remember { mutableStateOf(initialUser?.country ?: "United States") }
    var bio by remember { mutableStateOf(initialUser?.bio ?: "Living the Star Voice party vibes! 🌟") }
    var gender by remember { mutableStateOf(initialUser?.gender ?: "Star") }
    var isCountryPickerExpanded by remember { mutableStateOf(false) }

    val presetAvatars = listOf("avatar_user", "avatar_crown", "avatar_aria", "avatar_viktor", "avatar_layla", "avatar_support")

    // Automatic country flag resolution
    val currentCountryFlag = remember(selectedCountry) {
        CountryHelper.getFlag(selectedCountry)
    }

    fun processAndScanPhoto(uri: Uri) {
        rawSelectedUri = uri
        isCompressingAndUploading = true
        moderationResult = null
        uploadProgress = 0.1f

        coroutineScope.launch {
            // Compress & progress simulation
            delay(150)
            uploadProgress = 0.4f
            delay(150)
            uploadProgress = 0.75f

            // Real-time automatic safety moderation
            val result = ImageSafetyModerator.moderateImage(context, uri)
            uploadProgress = 1.0f
            delay(100)
            isCompressingAndUploading = false
            moderationResult = result

            if (result.isApproved) {
                avatarUriString = uri.toString()
                showCropControls = true
            } else {
                showCropControls = false
            }
        }
    }

    // Android Zero-Permission Gallery Picker
    val photoPickerLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.PickVisualMedia()
    ) { uri: Uri? ->
        if (uri != null) {
            processAndScanPhoto(uri)
        }
    }

    // Camera Capture Launcher
    val cameraLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.TakePicturePreview()
    ) { bitmap: Bitmap? ->
        if (bitmap != null) {
            val uri = CountryHelper.saveAndCompressBitmap(context, bitmap)
            processAndScanPhoto(uri)
        }
    }

    Surface(
        modifier = modifier
            .fillMaxSize()
            .statusBarsPadding()
            .navigationBarsPadding(),
        color = StarKingBgDark
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(16.dp)
        ) {
            // Top Header: Title & Close Button
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Column {
                    Text(
                        text = if (initialUser == null) "Create Your Profile 🌟" else "Edit Profile ✏️",
                        color = TextWhite,
                        fontWeight = FontWeight.Bold,
                        fontSize = 18.sp
                    )
                    Text(
                        text = "STAR VOICE CHAT • Step $currentStep of 3",
                        color = StarGoldLight,
                        fontSize = 11.sp,
                        fontWeight = FontWeight.SemiBold
                    )
                }

                IconButton(
                    onClick = onDismiss,
                    modifier = Modifier.testTag("setup_profile_close_btn")
                ) {
                    Icon(Icons.Default.Close, contentDescription = "Close", tint = TextWhite)
                }
            }

            Spacer(modifier = Modifier.height(14.dp))

            // Step Indicator Bar
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                StepIndicatorItem(
                    stepNumber = 1,
                    title = "Photo",
                    isActive = currentStep == 1,
                    isDone = currentStep > 1,
                    modifier = Modifier.weight(1f)
                )
                StepIndicatorItem(
                    stepNumber = 2,
                    title = "Details",
                    isActive = currentStep == 2,
                    isDone = currentStep > 2,
                    modifier = Modifier.weight(1f)
                )
                StepIndicatorItem(
                    stepNumber = 3,
                    title = "Preview",
                    isActive = currentStep == 3,
                    isDone = false,
                    modifier = Modifier.weight(1f)
                )
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Step Content
            AnimatedContent(
                targetState = currentStep,
                label = "profile_step_anim",
                modifier = Modifier.weight(1f)
            ) { step ->
                when (step) {
                    1 -> {
                        // --- STEP 1: PROFILE PHOTO ---
                        LazyColumn(
                            verticalArrangement = Arrangement.spacedBy(14.dp),
                            modifier = Modifier.fillMaxSize()
                        ) {
                            item {
                                Text(
                                    text = "Step 1: Choose or Upload Profile Photo",
                                    color = TextWhite,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 15.sp
                                )
                                Text(
                                    text = "Upload from Gallery or Camera. All photos undergo automatic real-time safety inspection.",
                                    color = TextMuted,
                                    fontSize = 11.sp
                                )
                            }

                            // Circular Photo Preview with Gold VIP Frame
                            item {
                                Column(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalAlignment = Alignment.CenterHorizontally
                                ) {
                                    Box(
                                        modifier = Modifier
                                            .size(130.dp)
                                            .clip(CircleShape)
                                            .border(
                                                3.dp,
                                                Brush.sweepGradient(listOf(StarGoldPrimary, Color(0xFFFF2B6D), StarGoldPrimary)),
                                                CircleShape
                                            )
                                            .background(StarKingSurfaceVariantDark),
                                        contentAlignment = Alignment.Center
                                    ) {
                                        if (avatarUriString.startsWith("http") || avatarUriString.startsWith("content://") || avatarUriString.startsWith("file://")) {
                                            AsyncImage(
                                                model = avatarUriString,
                                                contentDescription = "Profile Photo",
                                                contentScale = ContentScale.Crop,
                                                modifier = Modifier
                                                    .fillMaxSize()
                                                    .graphicsLayer(
                                                        scaleX = cropZoom,
                                                        scaleY = cropZoom
                                                    )
                                            )
                                        } else {
                                            AvatarView(
                                                avatarUrl = avatarUriString,
                                                nickname = nickname,
                                                size = 130.dp
                                            )
                                        }
                                    }

                                    Spacer(modifier = Modifier.height(8.dp))

                                    // Upload / Compress Progress Indicator
                                    if (isCompressingAndUploading) {
                                        Column(
                                            modifier = Modifier
                                                .fillMaxWidth()
                                                .padding(horizontal = 24.dp),
                                            horizontalAlignment = Alignment.CenterHorizontally
                                        ) {
                                            Text(
                                                text = "Compressing & Scanning Photo... ${(uploadProgress * 100).toInt()}%",
                                                color = StarGoldPrimary,
                                                fontSize = 11.sp,
                                                fontWeight = FontWeight.Bold
                                            )
                                            Spacer(modifier = Modifier.height(4.dp))
                                            LinearProgressIndicator(
                                                progress = { uploadProgress },
                                                color = StarGoldPrimary,
                                                trackColor = StarKingCardBorder,
                                                modifier = Modifier
                                                    .fillMaxWidth()
                                                    .height(6.dp)
                                                    .clip(RoundedCornerShape(3.dp))
                                            )
                                        }
                                    }

                                    // Moderation Verdict Banner
                                    moderationResult?.let { result ->
                                        Spacer(modifier = Modifier.height(8.dp))
                                        if (result.isApproved) {
                                            Row(
                                                verticalAlignment = Alignment.CenterVertically,
                                                modifier = Modifier
                                                    .clip(RoundedCornerShape(8.dp))
                                                    .background(LiveGreen.copy(alpha = 0.2f))
                                                    .border(1.dp, LiveGreen, RoundedCornerShape(8.dp))
                                                    .padding(horizontal = 10.dp, vertical = 5.dp)
                                            ) {
                                                Icon(Icons.Default.CheckCircle, contentDescription = null, tint = LiveGreen, modifier = Modifier.size(16.dp))
                                                Spacer(modifier = Modifier.width(6.dp))
                                                Text("Safety Verified: Community Safe ✓", color = LiveGreen, fontSize = 11.sp, fontWeight = FontWeight.Bold)
                                            }
                                        } else {
                                            Column(
                                                horizontalAlignment = Alignment.CenterHorizontally,
                                                modifier = Modifier
                                                    .clip(RoundedCornerShape(8.dp))
                                                    .background(DangerRed.copy(alpha = 0.2f))
                                                    .border(1.dp, DangerRed, RoundedCornerShape(8.dp))
                                                    .padding(horizontal = 12.dp, vertical = 6.dp)
                                            ) {
                                                Row(verticalAlignment = Alignment.CenterVertically) {
                                                    Icon(Icons.Default.Warning, contentDescription = null, tint = DangerRed, modifier = Modifier.size(16.dp))
                                                    Spacer(modifier = Modifier.width(6.dp))
                                                    Text("Inappropriate Photo Rejected ⛔", color = DangerRed, fontSize = 12.sp, fontWeight = FontWeight.Bold)
                                                }
                                                Text(
                                                    text = result.reason.ifBlank { "Detected explicit or policy-violating imagery. Please upload another photo." },
                                                    color = Color.White.copy(alpha = 0.85f),
                                                    fontSize = 10.sp,
                                                    textAlign = TextAlign.Center
                                                )
                                            }
                                        }
                                    }
                                }
                            }

                            // Upload Buttons (Gallery & Camera)
                            item {
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                                ) {
                                    OutlinedButton(
                                        onClick = {
                                            photoPickerLauncher.launch(
                                                PickVisualMediaRequest(ActivityResultContracts.PickVisualMedia.ImageOnly)
                                            )
                                        },
                                        shape = RoundedCornerShape(12.dp),
                                        colors = ButtonDefaults.outlinedButtonColors(contentColor = TextWhite),
                                        border = ButtonDefaults.outlinedButtonBorder().copy(brush = Brush.linearGradient(listOf(StarGoldPrimary, Color(0xFFFF2B6D)))),
                                        modifier = Modifier.weight(1f).height(46.dp).testTag("setup_upload_gallery_btn")
                                    ) {
                                        Icon(Icons.Default.PhotoLibrary, contentDescription = null, tint = StarGoldPrimary, modifier = Modifier.size(18.dp))
                                        Spacer(modifier = Modifier.width(6.dp))
                                        Text("From Gallery", fontSize = 12.sp, fontWeight = FontWeight.Bold)
                                    }

                                    OutlinedButton(
                                        onClick = { cameraLauncher.launch(null) },
                                        shape = RoundedCornerShape(12.dp),
                                        colors = ButtonDefaults.outlinedButtonColors(contentColor = TextWhite),
                                        border = ButtonDefaults.outlinedButtonBorder().copy(brush = Brush.linearGradient(listOf(NeonCyan, StarGoldPrimary))),
                                        modifier = Modifier.weight(1f).height(46.dp).testTag("setup_take_camera_btn")
                                    ) {
                                        Icon(Icons.Default.PhotoCamera, contentDescription = null, tint = NeonCyan, modifier = Modifier.size(18.dp))
                                        Spacer(modifier = Modifier.width(6.dp))
                                        Text("Take Photo", fontSize = 12.sp, fontWeight = FontWeight.Bold)
                                    }
                                }
                            }

                            // Zoom / Crop Controls
                            if (showCropControls && moderationResult?.isApproved == true) {
                                item {
                                    Card(
                                        colors = CardDefaults.cardColors(containerColor = StarKingSurfaceVariantDark),
                                        shape = RoundedCornerShape(12.dp),
                                        modifier = Modifier.fillMaxWidth()
                                    ) {
                                        Column(modifier = Modifier.padding(12.dp)) {
                                            Row(
                                                modifier = Modifier.fillMaxWidth(),
                                                horizontalArrangement = Arrangement.SpaceBetween,
                                                verticalAlignment = Alignment.CenterVertically
                                            ) {
                                                Text("Zoom & Crop", color = TextMuted, fontSize = 11.sp)
                                                Text("${String.format("%.1f", cropZoom)}x", color = StarGoldPrimary, fontSize = 11.sp, fontWeight = FontWeight.Bold)
                                            }
                                            Slider(
                                                value = cropZoom,
                                                onValueChange = { cropZoom = it },
                                                valueRange = 1f..3f,
                                                colors = SliderDefaults.colors(
                                                    thumbColor = StarGoldPrimary,
                                                    activeTrackColor = StarGoldPrimary
                                                )
                                            )
                                        }
                                    }
                                }
                            }

                            // Preset Avatars alternative
                            item {
                                Text(text = "Or Choose Preset Avatar:", color = TextMuted, fontSize = 12.sp)
                                Spacer(modifier = Modifier.height(6.dp))
                                LazyRow(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                                    items(presetAvatars) { av ->
                                        val isSelected = av == avatarUriString
                                        Box(
                                            modifier = Modifier
                                                .clip(CircleShape)
                                                .border(2.dp, if (isSelected) StarGoldPrimary else StarKingCardBorder, CircleShape)
                                                .clickable {
                                                    avatarUriString = av
                                                    moderationResult = ModerationResult(isApproved = true)
                                                }
                                                .padding(3.dp)
                                        ) {
                                            AvatarView(avatarUrl = av, nickname = nickname, size = 48.dp)
                                        }
                                    }
                                }
                            }

                            item {
                                Spacer(modifier = Modifier.height(10.dp))
                                Button(
                                    onClick = { currentStep = 2 },
                                    enabled = moderationResult?.isApproved != false && !isCompressingAndUploading,
                                    colors = ButtonDefaults.buttonColors(containerColor = StarGoldPrimary, contentColor = StarKingBgDark),
                                    shape = RoundedCornerShape(14.dp),
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .height(48.dp)
                                        .testTag("step1_next_btn")
                                ) {
                                    Text("Continue to Personal Info >", fontWeight = FontWeight.Bold, fontSize = 14.sp)
                                }
                            }
                        }
                    }

                    2 -> {
                        // --- STEP 2: PERSONAL INFORMATION ---
                        LazyColumn(
                            verticalArrangement = Arrangement.spacedBy(14.dp),
                            modifier = Modifier.fillMaxSize()
                        ) {
                            item {
                                Text(
                                    text = "Step 2: Personal Information",
                                    color = TextWhite,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 15.sp
                                )
                                Text(
                                    text = "Set up your public identity, display name, age, and country flag.",
                                    color = TextMuted,
                                    fontSize = 11.sp
                                )
                            }

                            // Unique Generated User ID (Automatic & Permanent)
                            item {
                                Row(
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .clip(RoundedCornerShape(12.dp))
                                        .background(StarKingSurfaceVariantDark)
                                        .border(1.dp, StarKingCardBorder, RoundedCornerShape(12.dp))
                                        .padding(12.dp),
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Row(verticalAlignment = Alignment.CenterVertically) {
                                        Text("🆔", fontSize = 16.sp)
                                        Spacer(modifier = Modifier.width(8.dp))
                                        Column {
                                            Text("Unique User ID", color = TextMuted, fontSize = 10.sp)
                                            Text("SV$autoGeneratedUserId", color = StarGoldPrimary, fontWeight = FontWeight.Black, fontSize = 14.sp)
                                        }
                                    }
                                    Box(
                                        modifier = Modifier
                                            .clip(RoundedCornerShape(6.dp))
                                            .background(Color(0xFF2C2456))
                                            .padding(horizontal = 6.dp, vertical = 2.dp)
                                    ) {
                                        Text("AUTOMATIC", color = NeonCyan, fontSize = 9.sp, fontWeight = FontWeight.Bold)
                                    }
                                }
                            }

                            // Display Name
                            item {
                                OutlinedTextField(
                                    value = nickname,
                                    onValueChange = { nickname = it },
                                    label = { Text("Display Name", color = TextMuted) },
                                    singleLine = true,
                                    colors = OutlinedTextFieldDefaults.colors(
                                        focusedBorderColor = StarGoldPrimary,
                                        unfocusedBorderColor = StarKingCardBorder,
                                        focusedTextColor = TextWhite,
                                        unfocusedTextColor = TextWhite
                                    ),
                                    shape = RoundedCornerShape(12.dp),
                                    modifier = Modifier.fillMaxWidth().testTag("setup_display_name_input")
                                )
                            }

                            // Age Selector (Numeric + Steppers)
                            item {
                                Column {
                                    Text(text = "Age", color = TextMuted, fontSize = 12.sp)
                                    Spacer(modifier = Modifier.height(6.dp))
                                    Row(
                                        modifier = Modifier
                                            .fillMaxWidth()
                                            .clip(RoundedCornerShape(12.dp))
                                            .background(StarKingSurfaceVariantDark)
                                            .border(1.dp, StarKingCardBorder, RoundedCornerShape(12.dp))
                                            .padding(horizontal = 14.dp, vertical = 8.dp),
                                        verticalAlignment = Alignment.CenterVertically,
                                        horizontalArrangement = Arrangement.SpaceBetween
                                    ) {
                                        Text("$age Years Old", color = TextWhite, fontWeight = FontWeight.Bold, fontSize = 14.sp)

                                        Row(
                                            verticalAlignment = Alignment.CenterVertically,
                                            horizontalArrangement = Arrangement.spacedBy(8.dp)
                                        ) {
                                            FilledTonalIconButton(
                                                onClick = { if (age > 18) age-- },
                                                colors = IconButtonDefaults.filledTonalIconButtonColors(containerColor = Color(0xFF2C2456))
                                            ) {
                                                Icon(Icons.Default.Remove, contentDescription = "Decrease Age", tint = TextWhite)
                                            }

                                            FilledTonalIconButton(
                                                onClick = { if (age < 99) age++ },
                                                colors = IconButtonDefaults.filledTonalIconButtonColors(containerColor = Color(0xFF2C2456))
                                            ) {
                                                Icon(Icons.Default.Add, contentDescription = "Increase Age", tint = TextWhite)
                                            }
                                        }
                                    }
                                }
                            }

                            // Country Selector with Automatic Country Flag
                            item {
                                Column {
                                    Text(text = "Country & Flag", color = TextMuted, fontSize = 12.sp)
                                    Spacer(modifier = Modifier.height(6.dp))

                                    Box {
                                        Row(
                                            modifier = Modifier
                                                .fillMaxWidth()
                                                .clip(RoundedCornerShape(12.dp))
                                                .background(StarKingSurfaceVariantDark)
                                                .border(1.dp, StarKingCardBorder, RoundedCornerShape(12.dp))
                                                .clickable { isCountryPickerExpanded = true }
                                                .padding(horizontal = 14.dp, vertical = 12.dp),
                                            verticalAlignment = Alignment.CenterVertically,
                                            horizontalArrangement = Arrangement.SpaceBetween
                                        ) {
                                            Row(verticalAlignment = Alignment.CenterVertically) {
                                                Text(currentCountryFlag, fontSize = 20.sp)
                                                Spacer(modifier = Modifier.width(10.dp))
                                                Text(selectedCountry, color = TextWhite, fontWeight = FontWeight.Bold, fontSize = 14.sp)
                                            }
                                            Icon(Icons.Default.ArrowDropDown, contentDescription = "Select Country", tint = StarGoldPrimary)
                                        }

                                        DropdownMenu(
                                            expanded = isCountryPickerExpanded,
                                            onDismissRequest = { isCountryPickerExpanded = false },
                                            modifier = Modifier.background(StarKingSurfaceDark).border(1.dp, StarKingCardBorder)
                                        ) {
                                            CountryHelper.COUNTRIES.forEach { countryInfo ->
                                                DropdownMenuItem(
                                                    text = {
                                                        Row(verticalAlignment = Alignment.CenterVertically) {
                                                            Text(countryInfo.flagEmoji, fontSize = 18.sp)
                                                            Spacer(modifier = Modifier.width(8.dp))
                                                            Text(countryInfo.name, color = TextWhite)
                                                        }
                                                    },
                                                    onClick = {
                                                        selectedCountry = countryInfo.name
                                                        isCountryPickerExpanded = false
                                                    }
                                                )
                                            }
                                        }
                                    }
                                }
                            }

                            // Optional Bio
                            item {
                                OutlinedTextField(
                                    value = bio,
                                    onValueChange = { if (it.length <= 160) bio = it },
                                    label = { Text("Bio (Optional)", color = TextMuted) },
                                    placeholder = { Text("Tell everyone what you love to talk about 🌟", color = TextSecondary) },
                                    maxLines = 3,
                                    supportingText = { Text("${bio.length}/160", color = TextMuted, fontSize = 10.sp) },
                                    colors = OutlinedTextFieldDefaults.colors(
                                        focusedBorderColor = StarGoldPrimary,
                                        unfocusedBorderColor = StarKingCardBorder,
                                        focusedTextColor = TextWhite,
                                        unfocusedTextColor = TextWhite
                                    ),
                                    shape = RoundedCornerShape(12.dp),
                                    modifier = Modifier.fillMaxWidth().testTag("setup_bio_input")
                                )
                            }

                            // Gender selection
                            item {
                                Text(text = "Gender", color = TextMuted, fontSize = 12.sp)
                                Spacer(modifier = Modifier.height(6.dp))
                                Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                                    listOf("Male", "Female", "Star").forEach { g ->
                                        val isSelected = g == gender
                                        Box(
                                            modifier = Modifier
                                                .clip(RoundedCornerShape(10.dp))
                                                .background(if (isSelected) StarGoldPrimary else StarKingSurfaceVariantDark)
                                                .clickable { gender = g }
                                                .padding(horizontal = 16.dp, vertical = 8.dp)
                                        ) {
                                            Text(
                                                text = g,
                                                color = if (isSelected) StarKingBgDark else TextWhite,
                                                fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Normal,
                                                fontSize = 12.sp
                                            )
                                        }
                                    }
                                }
                            }

                            item {
                                Spacer(modifier = Modifier.height(10.dp))
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                                ) {
                                    OutlinedButton(
                                        onClick = { currentStep = 1 },
                                        shape = RoundedCornerShape(14.dp),
                                        modifier = Modifier.weight(1f).height(48.dp)
                                    ) {
                                        Text("< Back", color = TextWhite)
                                    }

                                    Button(
                                        onClick = { currentStep = 3 },
                                        enabled = nickname.isNotBlank(),
                                        colors = ButtonDefaults.buttonColors(containerColor = StarGoldPrimary, contentColor = StarKingBgDark),
                                        shape = RoundedCornerShape(14.dp),
                                        modifier = Modifier.weight(1.5f).height(48.dp).testTag("step2_preview_btn")
                                    ) {
                                        Text("Preview Profile >", fontWeight = FontWeight.Bold, fontSize = 14.sp)
                                    }
                                }
                            }
                        }
                    }

                    3 -> {
                        // --- STEP 3: PROFILE PREVIEW ---
                        LazyColumn(
                            verticalArrangement = Arrangement.spacedBy(16.dp),
                            modifier = Modifier.fillMaxSize()
                        ) {
                            item {
                                Text(
                                    text = "Step 3: Profile Preview",
                                    color = TextWhite,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 15.sp
                                )
                                Text(
                                    text = "Review how other STAR VOICE users will see your profile card.",
                                    color = TextMuted,
                                    fontSize = 11.sp
                                )
                            }

                            // Profile Preview Card
                            item {
                                Card(
                                    colors = CardDefaults.cardColors(containerColor = Color(0xFF1E1838)),
                                    shape = RoundedCornerShape(24.dp),
                                    border = CardDefaults.outlinedCardBorder().copy(
                                        brush = Brush.linearGradient(
                                            listOf(StarGoldPrimary, Color(0xFFFF2B6D), StarGoldDark)
                                        )
                                    ),
                                    modifier = Modifier.fillMaxWidth()
                                ) {
                                    Column(
                                        modifier = Modifier
                                            .fillMaxWidth()
                                            .padding(20.dp),
                                        horizontalAlignment = Alignment.CenterHorizontally
                                    ) {
                                        // Profile Photo
                                        Box(
                                            modifier = Modifier
                                                .size(96.dp)
                                                .clip(CircleShape)
                                                .border(2.5.dp, StarGoldPrimary, CircleShape)
                                                .background(StarKingSurfaceVariantDark),
                                            contentAlignment = Alignment.Center
                                        ) {
                                            if (avatarUriString.startsWith("http") || avatarUriString.startsWith("content://") || avatarUriString.startsWith("file://")) {
                                                AsyncImage(
                                                    model = avatarUriString,
                                                    contentDescription = nickname,
                                                    contentScale = ContentScale.Crop,
                                                    modifier = Modifier.fillMaxSize().graphicsLayer(scaleX = cropZoom, scaleY = cropZoom)
                                                )
                                            } else {
                                                AvatarView(avatarUrl = avatarUriString, nickname = nickname, size = 96.dp)
                                            }
                                        }

                                        Spacer(modifier = Modifier.height(12.dp))

                                        // Name + Verified Badge
                                        Row(verticalAlignment = Alignment.CenterVertically) {
                                            Text(
                                                text = nickname,
                                                color = TextWhite,
                                                fontWeight = FontWeight.Black,
                                                fontSize = 19.sp
                                            )
                                            Spacer(modifier = Modifier.width(6.dp))
                                            Box(
                                                modifier = Modifier
                                                    .clip(CircleShape)
                                                    .background(StarGoldPrimary)
                                                    .size(16.dp),
                                                contentAlignment = Alignment.Center
                                            ) {
                                                Text("✓", color = Color.Black, fontSize = 10.sp, fontWeight = FontWeight.Bold)
                                            }
                                        }

                                        Spacer(modifier = Modifier.height(4.dp))

                                        // Country + Flag & Age & User ID
                                        Row(
                                            verticalAlignment = Alignment.CenterVertically,
                                            horizontalArrangement = Arrangement.spacedBy(8.dp)
                                        ) {
                                            Text("$currentCountryFlag $selectedCountry", color = NeonCyan, fontSize = 12.sp, fontWeight = FontWeight.SemiBold)
                                            Text("•", color = TextMuted)
                                            Text("$age yrs", color = TextChampagne, fontSize = 12.sp)
                                            Text("•", color = TextMuted)
                                            Text("UID: SV$autoGeneratedUserId", color = StarGoldLight, fontSize = 11.sp, fontWeight = FontWeight.Bold)
                                        }

                                        Spacer(modifier = Modifier.height(8.dp))

                                        // Bio
                                        if (bio.isNotBlank()) {
                                            Box(
                                                modifier = Modifier
                                                    .fillMaxWidth()
                                                    .clip(RoundedCornerShape(12.dp))
                                                    .background(Color(0xFF15112B))
                                                    .padding(horizontal = 12.dp, vertical = 8.dp)
                                            ) {
                                                Text(
                                                    text = "\"$bio\"",
                                                    color = TextChampagne,
                                                    fontSize = 12.sp,
                                                    textAlign = TextAlign.Center,
                                                    modifier = Modifier.fillMaxWidth()
                                                )
                                            }
                                        }

                                        Spacer(modifier = Modifier.height(14.dp))

                                        // Badges Row
                                        Row(
                                            modifier = Modifier.fillMaxWidth(),
                                            horizontalArrangement = Arrangement.SpaceAround
                                        ) {
                                            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                                Text("Level 1", color = StarGoldPrimary, fontWeight = FontWeight.Bold, fontSize = 12.sp)
                                                Text("New Star 🌟", color = TextMuted, fontSize = 10.sp)
                                            }
                                            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                                Text("0", color = TextWhite, fontWeight = FontWeight.Bold, fontSize = 12.sp)
                                                Text("Followers", color = TextMuted, fontSize = 10.sp)
                                            }
                                            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                                Text("0", color = TextWhite, fontWeight = FontWeight.Bold, fontSize = 12.sp)
                                                Text("Gifts", color = TextMuted, fontSize = 10.sp)
                                            }
                                        }
                                    }
                                }
                            }

                            // Action Buttons: Edit or Save & Continue
                            item {
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                                ) {
                                    OutlinedButton(
                                        onClick = { currentStep = 2 },
                                        shape = RoundedCornerShape(14.dp),
                                        colors = ButtonDefaults.outlinedButtonColors(contentColor = TextWhite),
                                        modifier = Modifier.weight(1f).height(48.dp)
                                    ) {
                                        Text("Edit ✏️", fontWeight = FontWeight.Bold)
                                    }

                                    Button(
                                        onClick = {
                                            onSaveProfile(nickname, age, selectedCountry, bio, avatarUriString, gender)
                                        },
                                        colors = ButtonDefaults.buttonColors(containerColor = StarGoldPrimary, contentColor = StarKingBgDark),
                                        shape = RoundedCornerShape(14.dp),
                                        modifier = Modifier.weight(1.5f).height(48.dp).testTag("save_and_continue_btn")
                                    ) {
                                        Text("Save & Continue 🚀", fontWeight = FontWeight.Bold, fontSize = 14.sp)
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun StepIndicatorItem(
    stepNumber: Int,
    title: String,
    isActive: Boolean,
    isDone: Boolean,
    modifier: Modifier = Modifier
) {
    Column(
        modifier = modifier,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Row(verticalAlignment = Alignment.CenterVertically) {
            Box(
                modifier = Modifier
                    .size(22.dp)
                    .clip(CircleShape)
                    .background(
                        when {
                            isDone -> LiveGreen
                            isActive -> StarGoldPrimary
                            else -> StarKingCardBorder
                        }
                    ),
                contentAlignment = Alignment.Center
            ) {
                if (isDone) {
                    Icon(Icons.Default.Check, contentDescription = null, tint = Color.Black, modifier = Modifier.size(12.dp))
                } else {
                    Text(
                        text = "$stepNumber",
                        color = if (isActive) StarKingBgDark else TextMuted,
                        fontSize = 11.sp,
                        fontWeight = FontWeight.Bold
                    )
                }
            }
            Spacer(modifier = Modifier.width(4.dp))
            Text(
                text = title,
                color = if (isActive || isDone) TextWhite else TextMuted,
                fontWeight = if (isActive) FontWeight.Bold else FontWeight.Normal,
                fontSize = 11.sp
            )
        }
        Spacer(modifier = Modifier.height(4.dp))
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .height(3.dp)
                .clip(RoundedCornerShape(1.5.dp))
                .background(
                    when {
                        isDone -> LiveGreen
                        isActive -> StarGoldPrimary
                        else -> StarKingCardBorder.copy(alpha = 0.4f)
                    }
                )
        )
    }
}
